import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Redirecting to App Store...",
  description: "Generated by create next app",
  other: {
    "al:ios:app_store_id": "1125517808",
    "al:ios:app_name": "Adjust Insights",
    "al:ios:url": "https://insights.go.link/privacy",
    "al:android:package": "com.adjust.insights",
    "al:android:url": "https://insights.go.link/privacy",
    "al:web:url": "https://insights.go.link/zalo-pc?to_store=true",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
